# Generated by Django 4.2.3 on 2023-09-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD_NP', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
